name: CI - Production

on:
  push:
    branches:
      - "main"

env:
  TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

      - name: Deploy Image to CapRrover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: "${{ secrets.CAPROVER_SERVER }}"
          app: "${{ secrets.APP_NAME }}"
          token: "${{ secrets.APP_TOKEN }}"
          image: ${{ env.IMAGE_URL }}
